name: bench

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: benchmark
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo criterion
        run: cargo install cargo-criterion

      - name: Benchmark
        run: cargo criterion --features full

      - name: Publish benchmark report
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/criterion/reports/
          CLEAN: true
