name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (features ${{ matrix.features }})
    strategy:
      fail-fast: false
      matrix:
        features:
          [
            "full",
            # 
            "merge",
            "sort",
            "preserve_order",
            # 
            "sort,merge",
            "merge,preserve_order",
            "sort,preserve_order",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Compile binaries
        run: >-
          cargo build
          --no-default-features
          --features "${{ matrix.features }}"
          --all-targets
