name: build

on: [push, pull_request]

jobs:
  matrix:
    uses: ./.github/workflows/matrix.yml

  debug:
    name: debug matrix
    runs-on: ubuntu-latest
    needs: [matrix]
    steps:
      - uses: actions/checkout@v2
      - name: print matrix
        run: |
          echo "${{ needs.matrix.outputs.matrix }}"

  build:
    name: build (features ${{ matrix.features }})
    runs-on: ubuntu-latest
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        features:
          include: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Compile binaries
        run: >-
          cargo build
          --no-default-features
          --features "${{ matrix.features }}"
          --all-targets
