name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (features ${{ matrix.features }})
    strategy:
      fail-fast: false
      matrix:
        features:
          [
            "",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Compile binaries
        run: >-
          cargo build
          --no-default-features
          --features "${{ matrix.features }}"
          --all-targets
