name: matrix

on: [workflow_call]

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compute feature matrix
        id: set-matrix
        run: |
          cargo install cargo-feature-combinations
          echo "::set-output name=matrix::$(cargo feature-combinations matrix)"
