name: test
on: [push, pull_request, workflow_call]
jobs:
  feature-matrix:
    uses: ./.github/workflows/feature-matrix.yml
  test:
    name: test ${{ matrix.package.name }} (${{ matrix.package.features }})
    runs-on: ubuntu-latest
    needs: [feature-matrix]
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJson(needs.feature-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: >-
          cargo test --package "${{ matrix.package.name }}" --features "${{ matrix.package.features }}" --all-targets
      - name: Lint
        run: >-
          cargo clippy --package "${{ matrix.package.name }}" --features "${{ matrix.package.features }}" --tests --benches --examples -- -Dclippy::all -Dclippy::pedantic
