name: test

on: [push, pull_request, workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test (features ${{ matrix.features }})
    strategy:
      fail-fast: false
      matrix:
        features:
          [
            "",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test
        run: >-
          cargo test
          --no-default-features
          --features "${{ matrix.features }}"
          --all-targets

      - name: Lint
        run: >-
          cargo clippy
          --tests
          --benches
          --examples
          -- -Dclippy::all -Dclippy::pedantic
