name: test

on: [push, pull_request, workflow_call]

jobs:
  matrix:
    uses: ./.github/workflows/matrix.yml
  
  test:
    name: test (features ${{ matrix.features }})
    runs-on: ubuntu-latest
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        features: ${{ fromJson(needs.matrix.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test
        run: >-
          cargo test
          --no-default-features
          --features "${{ matrix.features }}"
          --all-targets

      - name: Lint
        run: >-
          cargo clippy
          --no-default-features
          --features "${{ matrix.features }}"
          --tests
          --benches
          --examples
          -- -Dclippy::all -Dclippy::pedantic
